### PR TITLE
Kemo's debut

### PR DESCRIPTION
**Pull request by kenmoini**
How's it going y'all...

There are a couple adjustments I've made to the workshop docs...mostly styling, some JS refactoring for the footer, a lot of work on the footer really.....

- Added fiercesw.network to domain list in footer
- Fixed "Fork Me on GitHub" z-index
- Converted footer vars from table inception hell, to proper Bootstrap classed divs
- Fixed README.md to include the additional notation for Ruby+Asciidoctor
- Added some more...Red Hatty colours
- No, I don't normally spell colors like that
- Added js-cookie package to node_modules in theme
- Also gave the settings/variable/insert_pre_footer_name_here a bit of a responsive make over...scales between large and medium.  Small devices aren't showing the site as a whole well so we can tackle that beast later...maybe with an update to Bootstrap 4?
- Fixed google-code-prettify 404...
- Removed baseUrl from config.toml to enable local testing
- Refactored the Footer variable cookie part...now has a dynamic cookie path so different labs can be run by the same user with different credentials.  Because it's the little things in life that can really make your day.

There's a live demo I can tunnel via ngrok, it's up right now via: http://732a6c5a.ngrok.io/.  If it goes down (likely in a day or two) that will more than likely not point to my dev environment so ask me and I'll create another tunnel.

Let me know if this is gravy by the contributing guidelines, process for commenting script, tabs vs spaces, etc.

### CODE REVIEW

**Comment by ajacocks** [comment]
Ken, you have a minor bug:

In https://github.com/RedHatGov/redhatgov.github.io/pull/115/files#diff-618063036395fe9ee107f22b46c9eade , please uncomment `baseURL`.

I'll test once that is fixed.

**Comment by kenmoini** [comment]
Fix'd.  I removed the line, still failed.  Put it back in with redhatgov.io and boom.
I find it odd that it requires a baseURL to perform the tests...not a very portable test this way, and hard-codes absolute-to-the-domain URIs for all resources on generation.

**Comment by dischord01** [comment]
Ken, great job! Used to be a web developer?

**Comment by kenmoini** [comment]
Brad - Thank you!  Yep, come from the hay day of FrontPage extensions and Dreamweaver memory leaks, progressed a long way since then of course.  Done full stack dev on LEMP/LAMP, with RWD, PWA, LOLBBQ, WTFHAX, etc...happy to help collaborate in any way I can.

Also, good to see another jewel runner.

**Pull request merged**
