### PR TITLE
Hack scripts for project initialization

### PR DESCRIPTION
**Pull request by ecwpz91**
- Removed binary from repo to reduce size of checkout
- Added `hack`/ scripts to automate local `hugo` installation
- Updated README documentation for howto guidance
- Updated .travis.yml to not use sudo anymore

Items above will serve as baseline init scripts for future containerization.

### CODE REVIEW

**Comment by ecwpz91** [comment]
Not sure if this is possible, but could we just specify that gem and ruby are already installed beforehand, will have to look into on my free time...

Basically, was looking to remove the following lines from `.travis.yml`:

```
  - gem install asciidoctor
  - sudo pip install Pygments
```

**Comment by ecwpz91** [comment]
@dischord01 +1, it's meant for both local dev and TravisCI. Build passes see [link][1].

Also, reuse of these scripts in the future will for creating an s2i image that runs on OCP.

[1]: https://travis-ci.org/RedHatGov/redhatgov.github.io/builds/292343343?utm_source=github_status&utm_medium=notification

**Comment by ecwpz91** [comment]
P.S. might consider ansiblize first, then containerize, but either way works. Hugo container FTW!

**Comment by jaredhocutt** [comment]
For the time being, I believe the best option is to leave the binary in the repo until we can come up with a better option for the following 2 use cases:

1. Contributing content for the RedHatGov.io site should be easy. The binary is included in the repo to ensure contributors are using the same version the site is being built with, even as we upgrade versions.
2. The build in Travis CI needs access to the binary to do the build. Since we include the binary from number 1 above, it makes it easy to also do the build.

Use case 2 is the easy one to solve by having the Travis CI build just download the appropriate binary and unpack it. Use case 1 is the harder one to solve and is primarily why the binary is currently included.

Overall, the current size of the repo is ~73 MB, so not very large and clones fairly quickly.

**Comment by jaredhocutt** [comment]
I'm going to close this PR for now as there needs to be more discussion around making a change like this. Also, by just deleting the `hugo` binary from the repository does not reduce it's size as it's still part of the history at this point.

A rewrite of history would be required to reclaim that space causing everyone's clone to break. This is something that could be done, but guidance would need to be provided to everyone on how to handle this.

We can re-open or have a new PR created after some discussion happens around whether it's worth making this change and how we should approach it.

**Pull request closed without merging**
