### PR TITLE
New screenshots and updates to labs 1 and 8

### PR DESCRIPTION
**Pull request by jottofar**
Added image to lab 1.
Added new text and images to lab 8.

### CODE REVIEW

**Comment by jaredhocutt** [comment]
@jottofar Did you mean to create a pull request to merge your `docs-ocpnodejs` branch into a branch by the same name in the `RedHatGov` repo or did you intend to merge it into the `docs` branch in the `RedHatGov` repo?

**Comment by jottofar** [comment]
hi jaredhocutt, believe it was correct as I'm wanting to push it to dudash for review first.

**Comment by jaredhocutt** [comment]
@jottofar Sounds good. I have assigned @dudash as a reviewer.

I'll leave it up to you if you want to change the branch to `docs` so that once you and @dudash work out the changes it can be commited upstream or if you want to create a separate pull request to go from the `docs-ocpnodejs` to the `docs` branch afterwards.

**Comment by jaredhocutt** [comment]
@jottofar @dudash Sync up with @jvanmeter as he might also be doing some work to convert some of the same content.

**Comment by jottofar** [comment]
@dudash @jaredhocutt  @jvanmeter , workshop openshift_101_dcmetromap?

**Comment by jvanmeter** [comment]
jotofar,

I am roughly 60-70% done converting
https://github.com/ecwpz91/openshift-workshops.git which is a fork of
Jason's https://github.com/dudash/openshift-workshops.git repo.  I believe
that Michael Surbey (ecwpz91) made some changes which differs from Jason's
repo slightly.

If you are converting the gh-pages branch for
https://github.com/dudash/openshift-workshops.git, then we are converting
the same workshop material.  Is there a way in which we can collaborate if
this is the case?

Kind regards,

Jonathan

**Comment by jottofar** [comment]
@jvanmeter on a call now but can I call you after 2 to discuss?

**Comment by dudash** [comment]
@jaredhocutt I was planning on keeping it in docs-ocpnodejs branch until it was complete and then merge or PR from there into docs.

**Comment by jottofar** [comment]
@dudash @jaredhocutt, @jvanmeter says he's been converting also and wants to collab, can we get on a call and hash this out

**Comment by dudash** [comment]
@jvanmeter - sorry was unaware of that.  But we have a soonish deadline to have this ready for a customer workshop on 6/21.

Do you know the differences in ecwpz91 from original?  I'm happy to agree to merge these together, but I'd suggest that we do that merge after @jottofar 's workshop (unless it's easy & low risk)

**Comment by jottofar** [comment]
@jvanmeter, I like @dudash 's idea, i'd like to simply get this done

**Comment by jvanmeter** [comment]
@jottofar - Are you saying that you do not want to collaborate on the
conversion?

@dudash - I wish that I knew which changes were made.  There were some
refinements made, based on my recollection.  My suggestion is to reach out
to Michael for specifics.

**Comment by jottofar** [comment]
@jvanmeter I'm pretty far along so I just need to press and get done, we can sync up afterwards

**Pull request merged**
