### PR TITLE
Round 2 - FIGHT!

### PR DESCRIPTION
**Pull request by kenmoini**
Yep, back at it again...

This time, the bulk of what I've done is...

- Created a Fierce Software theme, two in fact, a light and a dark theme.  Hopefully between the three there's a good example of what you can and can't do with a theme, vs layout since Hugo doesn't really adhere to a real MVC structure...
- Update the redhatgov theme with some responsive code
- Update the layout with some responsive code
- Create a Font Awesome shortcode...in content, use with `{{< fa class="fa-dashboard" style="margin:1rem" >}}` or `{{< fa "fa-dashboard" "margin:1rem" >}}`, OR simply `{{< fa fa-dashboard >}}`, arg2/style is optional
- Oh and if that wasn't enough responsive-ness for you, there's now some simple JS to make all images responsive.  Boosh.

**layouts/index.html** - Added hidden-xs class to Fork banner, added responsive classes where needed
**layouts/_default/lab.html** - Made the lab layout responsive...
**layouts/partials/footer/footer.html** - Added some JS to make all images responsive on DOM ready
**layouts/taxonomy/workshop.html** - Made the workshop layout responsive...
**layouts/section/events.html** - Made the events layout responsive...
**layouts/shortcodes/fa.html** - Created new Font Awesome shortcode, use with {{< fa class="fa-dashboard" style="margin:1rem" >}} or {{< fa "fa-dashboard" "margin:1rem" >}}, OR simply {{< fa fa-dashboard >}}, arg2/style is optional
**themes/fiercesw** - Created dedicated Fierce Software theme, light version
**themes/fiercesw-dark** - Created dedicated Fierce Software theme, dark version
**themes/redhatgov** - Update files to add responsive classes.  Added some CSS to the footer
**CONTRIBUTING.md** - Fixed line for cloning

Alrighty, now that things are pretty pretty, time to make some Integration workshops...

### CODE REVIEW

**Comment by kenmoini** [comment]
Oh yeah, I forgot to tag it in the PR but this resolves #33

**Comment by ajacocks** [comment]
I'm reviewing this, and will review ASAP.  No guarantees for this week, but I'll try.

**Comment by kenmoini** [comment]
@ajacocks No worries, take your time, lemme know if you have any questions, etc.

**Comment by ajacocks** [comment]
Brad, could you take a look at this one?  I'm really not very knowledgeable about web coding.

**Comment by kenmoini** [comment]
Hmm, I have a suggestion that might make everyone's lives easier...

Most of the tracked changes are from the installed node_modules. Maybe if there were a step during the documented initial deployment process to alert the user to run 'npm install' then we could easily add "node_modules" folder to the gitignore file, thus limiting PRs like this to only the few hundred lines of actual code revisions...

Between that and the numerous other changes over the last few months since I put in this PR that might cause merge conflicts, it's probably best to close and dismiss this PR and I'll submit the improvements and fixes again when I have time.

Thoughts?

**Comment by kenmoini** [comment]
Closing PR...looking back it was kinda of a large set of changes, so I'll look to breaking some of them up into smaller PRs here soon enough.

Also, there was mention of discussion around the refactoring of the platform soon...I'd like to be included in that discussion if at all possible.  It'd be great to move away from something that relies on NPM...I'll be happy to lend my skills in shoring up the web-end.

**Pull request closed without merging**
