### PR TITLE
Update example workshop with info on how to get started

### PR DESCRIPTION
**Pull request by jaredhocutt**
I have updated the example workshop with content on how someone would go about creating a new workshop by using the example workshop as a starting point.

I'd like to get someone to look over the content and formatting and get any feedback before deploying the content.

### CODE REVIEW

**Comment by dischord01** [comment]
I think example pages that looks like a full workshop would be good:  setup, exercise1.0, exercise1.2, wrapup. And a additional page as the kitchen sink example.

**Comment by jaredhocutt** [comment]
@dischord01 100% agree. There's still quite a bit more I'd like to add to the example workshop. I'm attempting to add bits and pieces as I have time.

My goal for this pull request is to have the details on how to create a new workshop from scratch in the most basic sense (i.e. what are the bare minimums to get started).

**Comment by epe105** [comment]
Looks awesome!  It's super easy to follow.  Maybe add another step for pushing to your origin and creating the pull request.

**Comment by jaredhocutt** [comment]
@epe105 That's a great idea! I'll get that added over the next few days and create a new pull request since @dischord01 already merged this one in.

**Pull request merged**
